create extension if not exists pgcrypto;

create or replace function public.touch_updated_date()
returns trigger
language plpgsql
as $$
begin
  new.updated_date = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role text not null default 'User',
  department text not null default 'Operations',
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  project_code text not null unique,
  project_name text not null,
  description text not null default '',
  owner text not null,
  department text not null,
  start_date date not null,
  due_date date not null,
  status text not null,
  priority text not null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.sop_folders (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.sops (
  id bigint generated by default as identity primary key,
  sop_code text not null unique,
  sop_name text not null,
  document_type text not null default 'Procedure',
  category text not null default '',
  department text not null,
  purpose text not null default '',
  scope text not null default '',
  steps text not null default '',
  content text not null default '',
  tags jsonb not null default '[]'::jsonb,
  owner text not null,
  responsibility_level text not null default 'L1 User / Staff',
  responsible_user text not null default '',
  process_owner text not null default '',
  control_owner text not null default '',
  business_criticality text not null default 'Medium',
  expiry_date date,
  business_unit text not null default '',
  process_group text not null default '',
  process_name text not null default '',
  sub_process text not null default '',
  related_policies jsonb not null default '[]'::jsonb,
  related_controls jsonb not null default '[]'::jsonb,
  related_systems jsonb not null default '[]'::jsonb,
  upstream_process text not null default '',
  downstream_process text not null default '',
  control_objective text not null default '',
  control_frequency text not null default '',
  evidence_required jsonb not null default '[]'::jsonb,
  risk_mitigated text not null default '',
  compliance_requirement text not null default '',
  audit_owner text not null default '',
  auditor text not null default '',
  exception_handling text not null default '',
  required_approvals jsonb not null default '[]'::jsonb,
  reviewer text not null default '',
  approver text not null default '',
  approval_status text not null default 'Draft',
  review_cycle_months integer not null default 12,
  next_review_date date,
  change_summary text not null default '',
  change_reason text not null default '',
  risk_level text not null default 'Medium',
  access_level text not null default 'Internal',
  retention_period text not null default '',
  distribution_list jsonb not null default '[]'::jsonb,
  training_required boolean not null default false,
  training_audience jsonb not null default '[]'::jsonb,
  controlled_copy_location text not null default '',
  version text not null,
  effective_date date not null,
  status text not null,
  attachment_url text not null default '',
  image_urls jsonb not null default '[]'::jsonb,
  folder_id bigint references public.sop_folders(id) on delete set null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.sop_files (
  id bigint generated by default as identity primary key,
  sop_id bigint references public.sops(id) on delete cascade,
  folder_id bigint references public.sop_folders(id) on delete set null,
  file_name text not null,
  file_type text not null,
  file_url text not null,
  created_date timestamptz not null default now()
);

create table if not exists public.sop_approvals (
  id bigint generated by default as identity primary key,
  sop_id bigint not null references public.sops(id) on delete cascade,
  reviewer text not null,
  approver text not null,
  decision text not null,
  comment text not null default '',
  created_date timestamptz not null default now()
);

create table if not exists public.sop_training_acknowledgements (
  id bigint generated by default as identity primary key,
  sop_id bigint not null references public.sops(id) on delete cascade,
  user_name text not null,
  role text not null default '',
  note text not null default '',
  acknowledged_date timestamptz not null default now()
);

create table if not exists public.sop_lifecycle_events (
  id bigint generated by default as identity primary key,
  sop_id bigint not null references public.sops(id) on delete cascade,
  from_status text not null,
  to_status text not null,
  user_name text not null,
  reason text not null default '',
  created_date timestamptz not null default now()
);

create table if not exists public.sop_evidence (
  id bigint generated by default as identity primary key,
  sop_id bigint not null references public.sops(id) on delete cascade,
  evidence_name text not null,
  evidence_type text not null,
  evidence_url text not null default '',
  control_reference text not null default '',
  uploaded_by text not null,
  created_date timestamptz not null default now()
);

create table if not exists public.sop_exceptions (
  id bigint generated by default as identity primary key,
  sop_id bigint not null references public.sops(id) on delete cascade,
  exception_code text not null unique,
  reason text not null,
  impact text not null default '',
  workaround text not null default '',
  owner text not null,
  due_date date not null,
  approval_required boolean not null default false,
  closure_evidence text not null default '',
  status text not null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  task_code text not null unique,
  task_title text not null,
  project_id bigint not null references public.projects(id) on delete cascade,
  work_detail text not null,
  sop_id bigint references public.sops(id) on delete set null,
  assigned_to text not null,
  priority text not null,
  start_date date not null,
  due_date date not null,
  status text not null,
  progress_percent integer not null default 0,
  attachment_url text not null default '',
  created_by text not null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  user_name text not null,
  comment text not null,
  created_date timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  user_name text not null,
  action text not null,
  details text not null,
  created_date timestamptz not null default now()
);

create table if not exists public.transformations (
  id bigint generated by default as identity primary key,
  discovery_code text not null unique,
  client_name text not null,
  department text not null,
  current_workflow text not null,
  pain_points jsonb not null default '[]'::jsonb,
  repetitive_tasks jsonb not null default '[]'::jsonb,
  documents_used jsonb not null default '[]'::jsonb,
  stakeholders jsonb not null default '[]'::jsonb,
  ai_use_cases jsonb not null default '[]'::jsonb,
  proposed_solution text not null default '',
  implementation_plan text not null default '',
  training_needed text not null default '',
  status text not null,
  owner text not null,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

drop trigger if exists touch_profiles_updated_date on public.profiles;
create trigger touch_profiles_updated_date before update on public.profiles for each row execute function public.touch_updated_date();
drop trigger if exists touch_projects_updated_date on public.projects;
create trigger touch_projects_updated_date before update on public.projects for each row execute function public.touch_updated_date();
drop trigger if exists touch_sop_folders_updated_date on public.sop_folders;
create trigger touch_sop_folders_updated_date before update on public.sop_folders for each row execute function public.touch_updated_date();
drop trigger if exists touch_sops_updated_date on public.sops;
create trigger touch_sops_updated_date before update on public.sops for each row execute function public.touch_updated_date();
drop trigger if exists touch_sop_exceptions_updated_date on public.sop_exceptions;
create trigger touch_sop_exceptions_updated_date before update on public.sop_exceptions for each row execute function public.touch_updated_date();
drop trigger if exists touch_tasks_updated_date on public.tasks;
create trigger touch_tasks_updated_date before update on public.tasks for each row execute function public.touch_updated_date();
drop trigger if exists touch_transformations_updated_date on public.transformations;
create trigger touch_transformations_updated_date before update on public.transformations for each row execute function public.touch_updated_date();

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.sop_folders enable row level security;
alter table public.sops enable row level security;
alter table public.sop_files enable row level security;
alter table public.sop_approvals enable row level security;
alter table public.sop_training_acknowledgements enable row level security;
alter table public.sop_lifecycle_events enable row level security;
alter table public.sop_evidence enable row level security;
alter table public.sop_exceptions enable row level security;
alter table public.tasks enable row level security;
alter table public.task_comments enable row level security;
alter table public.activity_logs enable row level security;
alter table public.transformations enable row level security;

create policy "profiles read authenticated" on public.profiles for select to authenticated using (true);
create policy "profiles insert own row" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "profiles update own row" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy "projects portfolio crud" on public.projects for all to authenticated using (true) with check (true);
create policy "sop folders portfolio crud" on public.sop_folders for all to authenticated using (true) with check (true);
create policy "sops portfolio crud" on public.sops for all to authenticated using (true) with check (true);
create policy "sop files portfolio crud" on public.sop_files for all to authenticated using (true) with check (true);
create policy "sop approvals portfolio crud" on public.sop_approvals for all to authenticated using (true) with check (true);
create policy "sop training portfolio crud" on public.sop_training_acknowledgements for all to authenticated using (true) with check (true);
create policy "sop lifecycle portfolio crud" on public.sop_lifecycle_events for all to authenticated using (true) with check (true);
create policy "sop evidence portfolio crud" on public.sop_evidence for all to authenticated using (true) with check (true);
create policy "sop exceptions portfolio crud" on public.sop_exceptions for all to authenticated using (true) with check (true);
create policy "tasks portfolio crud" on public.tasks for all to authenticated using (true) with check (true);
create policy "task comments portfolio crud" on public.task_comments for all to authenticated using (true) with check (true);
create policy "activity logs portfolio crud" on public.activity_logs for all to authenticated using (true) with check (true);
create policy "transformations portfolio crud" on public.transformations for all to authenticated using (true) with check (true);
